import express from 'express';
import XLSX from 'xlsx';
import { requireAdmin, requireScreen } from '../middleware/auth.js';
import { buildRegistrationReport, parseFilters } from '../reportData.js';
import { buildReportPdf } from '../reportPdf.js';

const router = express.Router();
const SOCIETY_NAME = 'REACH Pravasi Welfare Society';

router.use(requireAdmin);

// On-screen report: summary, breakdowns by country / Panchayath / plan / status, member list.
router.get('/registrations', requireScreen('reports'), async (req, res, next) => {
  try {
    res.json(await buildRegistrationReport(parseFilters(req.query)));
  } catch (e) { next(e); }
});

const fileStamp = () => new Date().toISOString().slice(0, 10);

const fmtDate = (d) => {
  if (!d) return '';
  const dt = d instanceof Date ? d : new Date(d);
  return Number.isNaN(dt.getTime()) ? String(d).slice(0, 10) : dt.toISOString().slice(0, 10);
};

const GROUP_HEAD = ['Registrations', 'Active', 'Pending', 'Expats', 'Paid', 'Unpaid', 'Expected Fees (₹)', 'Collected (₹)', 'Outstanding (₹)'];
const groupCells = (r) => [r.registrations, r.active, r.pending, r.expats, r.paid_count, r.unpaid_count, r.expected_fees, r.collected, r.outstanding];

function sheet(rows, widths) {
  const ws = XLSX.utils.aoa_to_sheet(rows);
  if (widths) ws['!cols'] = widths.map((wch) => ({ wch }));
  return ws;
}

// Real .xlsx workbook (not CSV) with one sheet per breakdown, so the report opens in Excel
// with proper numeric cells that can be summed / pivoted.
router.get('/registrations/export.xlsx', requireScreen('reports'), async (req, res, next) => {
  try {
    const report = await buildRegistrationReport(parseFilters(req.query));
    const s = report.summary;
    const wb = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(wb, sheet([
      [`${SOCIETY_NAME} — Registration & Payments Report`],
      ['Generated', new Date(report.generated_at).toLocaleString('en-IN')],
      ['Generated by', req.adminUser.full_name || req.adminUser.username],
      ['Filters', report.filter_text],
      [],
      ['Metric', 'Value'],
      ['Registrations', s.registrations],
      ['Active members', s.active],
      ['Pending applications', s.pending],
      ['Expats', s.expats],
      ['Payments received (members paid)', s.paid_count],
      ['Unpaid', s.unpaid_count],
      ['Expected fees (₹)', s.expected_fees],
      ['Fees collected (₹)', s.collected],
      ['Outstanding (₹)', s.outstanding],
      ['Marked Paid without a payment record (full fee assumed)', s.unrecorded_paid],
    ], [52, 60]), 'Summary');

    XLSX.utils.book_append_sheet(wb, sheet([
      ['Country', ...GROUP_HEAD],
      ...report.byCountry.map((r) => [r.country, ...groupCells(r)]),
      ['Total', ...groupCells(s)],
    ], [28, 14, 10, 10, 10, 10, 10, 18, 16, 16]), 'By Country');

    XLSX.utils.book_append_sheet(wb, sheet([
      ['Panchayath / Municipality', ...GROUP_HEAD],
      ...report.byPanchayath.map((r) => [r.panchayath, ...groupCells(r)]),
      ['Total', ...groupCells(s)],
    ], [30, 14, 10, 10, 10, 10, 10, 18, 16, 16]), 'By Panchayath');

    XLSX.utils.book_append_sheet(wb, sheet([
      ['Membership Plan', ...GROUP_HEAD],
      ...report.byPlan.map((r) => [r.plan_name, ...groupCells(r)]),
      ['Total', ...groupCells(s)],
    ], [28, 14, 10, 10, 10, 10, 10, 18, 16, 16]), 'By Plan');

    XLSX.utils.book_append_sheet(wb, sheet([
      ['Status', 'Registrations', 'Collected (₹)'],
      ...report.byStatus.map((r) => [r.status, r.count, r.collected]),
      ['Total', s.registrations, s.collected],
    ], [24, 14, 16]), 'By Status');

    XLSX.utils.book_append_sheet(wb, sheet([
      ['#', 'Reference No', 'Membership ID', 'Name', 'Place', 'Panchayath / Municipality', 'Country', 'Expat',
        'Plan', 'Status', 'Payment Status', 'Membership Fee (₹)', 'Amount Paid (₹)', 'Balance (₹)', 'Payment Recorded', 'Paid On',
        'Payment Method', 'Receipt No', 'WhatsApp', 'E-mail', 'Registered On'],
      ...report.members.map((m, i) => [
        i + 1, m.reference_no, m.membership_id || '', m.name, m.place, m.panchayath, m.country, m.is_expat ? 'Yes' : 'No',
        m.plan_name, m.status, m.payment_status, m.membership_fee, m.paid_amount ?? '', m.balance,
        m.payment_recorded ? 'Yes' : (m.payment_status === 'Paid' ? 'No (full fee assumed)' : ''), fmtDate(m.paid_on),
        m.payment_method || '', m.receipt_number || '', m.whatsapp_number || '', m.email || '', fmtDate(m.created_at),
      ]),
    ], [5, 18, 18, 26, 18, 26, 18, 7, 22, 20, 14, 16, 16, 12, 22, 12, 16, 16, 16, 28, 14]), 'Members');

    const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="registration-report-${fileStamp()}.xlsx"`);
    res.send(buf);
  } catch (e) { next(e); }
});

router.get('/registrations/export.pdf', requireScreen('reports'), async (req, res, next) => {
  try {
    const report = await buildRegistrationReport(parseFilters(req.query));
    const pdf = await buildReportPdf({
      report,
      societyName: SOCIETY_NAME,
      generatedBy: req.adminUser.full_name || req.adminUser.username,
    });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="registration-report-${fileStamp()}.pdf"`);
    res.send(pdf);
  } catch (e) { next(e); }
});

export default router;
